=== damdravic/Java6DamianDragos/Java6DamianDragos/src/userXML/usersDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT USERS (USER)*>
<!ELEMENT USER (USERNAME|PASSWORD|USERROLE)*>
<!ELEMENT USERNAME (#PCDATA)>
<!ELEMENT PASSWORD (#PCDATA)>
<!ELEMENT USERROLE (#PCDATA)>

=== damdravic/Java6DamianDragos/Java6DamianDragos/src/userXML/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE USERS SYSTEM "usersDTD.dtd">


<USERS>
    <USER> 
    <USERNAME>GEORGE</USERNAME>
    <PASSWORD>123</PASSWORD>
    <USERROLE>ADMIN</USERROLE>
    </USER>
    <USER> 
    <USERNAME>TUDOR</USERNAME>
    <PASSWORD>456</PASSWORD>
     <USERROLE>USER</USERROLE>
    </USER>
    <USER> 
    <USERNAME>ANA</USERNAME>
    <PASSWORD>789</PASSWORD>
     <USERROLE>USER</USERROLE>
    </USER>
    <USER> 
    <USERNAME>IOANA</USERNAME>
    <PASSWORD>ABC</PASSWORD>
     <USERROLE>USER</USERROLE>
    </USER>
</USERS>
